### ISSUE TITLE
code in jsRepeat treat as jsxRegion

### ISSUE THREAD

**Issue by SirAnthony** [neoclide/vim-jsx-improve#22]
Hello, in case below all code after the <num will be treated as jsxRegion. Highlighting completely broken after this.
```
for (let i=0; i<num; i++)
    code
```
![capture3](https://user-images.githubusercontent.com/316434/32220317-f3858200-be39-11e7-8a4a-083638d12374.PNG)

**Comment by chemzqm** [comment]
One solution is always have space after `<` when it's not a tag, since it's hard to fix this problem with the regex hack of vim,  you can send a PR if you would like to help:
```
      \ matchgroup=jsxTag start=+<[^ }/!?<>"'=:]\@=+
```
You can use tools like https://github.com/prettier/prettier to auto format your code on save if you're not used to type the space.

**Comment by SirAnthony** [comment]
It is all matters of coding conventions. I [fixed](https://github.com/SirAnthony/vim-jsx-improve/commit/e4ef060092e1994322c1d6e18f238033fb4b2a45) it by looking at vim-jsx code, which working correctly.
Sorry, do not have enough time to make proper pr, without commits upstream do not really need.
